
CREATE TABLE IF NOT EXISTS kilo (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    observation TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);