import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Metadata, Viewport } from "next";
import Providers from "@/providers/Providers";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  themeColor: "#000000",
  initialScale: 1,
  width: "device-width",
  viewportFit: "cover",
  maximumScale: 1,
};

export const metadata: Metadata = {
  title: "KILO Dashboard",
  description: "Generated by create next app",
  appleWebApp: {
    statusBarStyle: "black-translucent",
  },
  // ...other metadata
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href='/site.webmanifest' />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}              
        </Providers>   
        <Toaster 
          position="top-center"
          expand={true}
          richColors={true}
          toastOptions={{
            style: {
              background: 'white',
              border: '1px solid #e5e7eb',
              color: '#374151'
            },
            className: 'class',
            descriptionClassName: 'description-class',
          }}
        />          
      </body>
    </html>
  );
}